version: "3"
services:
  nosql-db:
    image: mvertes/alpine-mongo
    ports:
      - "27018:27017"
    container_name: nosql-db
    volumes:
      - ./db/:/data/db

  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'

  Course:
    build:
      dockerfile: Dockerfile
      context: ./Course
    container_name: Course
    ports:
      - "8006:8006"
    restart: always
    depends_on:
      - "nosql-db"
      - "rabbitmq"
    volumes:
      - .:/app
      - /app/courses/node_modules

    env_file:
      - ./courses/.env.dev
  CourseEnrollment:
    build:
      dockerfile: Dockerfile
      context: ./CourseEnrollment
    container_name: CourseEnrollment
    ports:
      - "8003:8003"
    restart: always
    depends_on:
      - "nosql-db"
      - "rabbitmq"
    volumes:
      - .:/app
      - /app/coursebuy/node_modules
    env_file:
      - ./coursebuy/.env.dev
  User:
    build:
      dockerfile: Dockerfile
      context: ./User
    container_name: User
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - "nosql-db"
      - "rabbitmq"
    volumes:
      - .:/app/
      - /app/user/node_modules
    env_file:
      - ./user/.env.dev
  Payment:
    build:
      dockerfile: Dockerfile
      context: ./Payment
    container_name: Payment
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - "nosql-db"
      - "rabbitmq"
    volumes:
      - .:/app/
      - /app/payment/node_modules
    env_file:
      - ./payment/.env.dev
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - courses
      - coursebuy
      - user
      - payment
    ports:
      - 80:80
