version: "2.26.1"
services:
  nosql-db:
    image: mvertes/alpine-mongo
    ports:
      - "27018:27017"
    container_name: nosql-db
    volumes:
      - ./db/:/data/db

  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'

  course:
    build:
      dockerfile: Dockerfile
      context: ./course
    container_name: course
    ports:
      - "8006:8006"
    restart: always
    depends_on:
      - "nosql-db"
      - "rabbitmq"
    volumes:
      - .:/app
      - /app/course/node_modules

    env_file:
      - ./course/.env.dev
  courseenrollment:
    build:
      dockerfile: Dockerfile
      context: ./courseenrollment
    container_name: courseenrollment
    ports:
      - "8007:8007"
    restart: always
    depends_on:
      - "nosql-db"
      - "rabbitmq"
    volumes:
      - .:/app
      - /app/courseenrollment/node_modules
    env_file:
      - ./courseenrollment/.env.dev
  user:
    build:
      dockerfile: Dockerfile
      context: ./user
    container_name: user
    ports:
      - "8005:8005"
    restart: always
    depends_on:
      - "nosql-db"
      - "rabbitmq"
    volumes:
      - .:/app/
      - /app/user/node_modules
    env_file:
      - ./user/.env.dev
  payment:
    build:
      dockerfile: Dockerfile
      context: ./payment
    container_name: payment
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - "nosql-db"
      - "rabbitmq"
    volumes:
      - .:/app/
      - /app/payment/node_modules
    env_file:
      - ./payment/.env.dev
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - course
      - courseenrollment
      - user
      - payment
    ports:
      - 80:80
